# -*- coding: utf-8 -*-
"""automate_Ardinda_Nur_Ramadhani

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aeWWK1ot6FtYPNJ0FcB9CamWh362czEf
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

def load_data(path):
    df = pd.read_csv(path)
    return df

def clean_data(df):
    df = df.copy()

    # Drop kolom tidak relevan
    if 'customerID' in df.columns:
        df.drop(columns=['customerID'], inplace=True)

    # Konversi TotalCharges ke numerik
    df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

    # Handle missing values
    df['TotalCharges'] = df['TotalCharges'].fillna(
        df['TotalCharges'].median()
    )

    # Cek & hapus duplikat (defensive)
    df.drop_duplicates(inplace=True)

    # Binning tenure
    df['tenure_group'] = pd.cut(
        df['tenure'],
        bins=[0, 12, 24, 48, 72],
        labels=['Low', 'Medium', 'High', 'Very High']
    )

    return df

def split_features_target(df):

    X = df.drop(columns=['Churn'])
    y = df['Churn']

    return X, y

def build_preprocessor(X):

    # Kolom numerik
    num_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']

    # Kolom kategorikal
    cat_cols = X.select_dtypes(include='object').columns

    # Pipeline numerik
    numeric_pipeline = Pipeline(steps=[
        ('scaler', StandardScaler())
    ])

    # Pipeline kategorikal
    categorical_pipeline = Pipeline(steps=[
        ('encoder', OneHotEncoder(drop='first', handle_unknown='ignore'))
    ])

    # ColumnTransformer
    preprocessor = ColumnTransformer(transformers=[
        ('num', numeric_pipeline, num_cols),
        ('cat', categorical_pipeline, cat_cols)
    ])

    return preprocessor

def save_preprocessed_data(X, y, output_path):

    if hasattr(X, "toarray"):
        X = X.toarray()

    df_processed = pd.DataFrame(X)
    df_processed['Churn'] = y.values

    df_processed.to_csv(output_path, index=False)

def preprocess_data(path, output_path):
    df = load_data(path)
    df = clean_data(df)

    X, y = split_features_target(df)

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42,
        stratify=y
    )

    preprocessor = build_preprocessor(X_train)

    X_train_processed = preprocessor.fit_transform(X_train)
    X_test_processed = preprocessor.transform(X_test)

    save_preprocessed_data(
        X_train_processed,
        y_train,
        output_path
    )

    return X_train_processed, X_test_processed, y_train, y_test

if __name__ == "__main__":

    input_path = "telco_customer_churn_raw.csv"
    output_path = "preprocessing/telco_customer_churn_preprocessing.csv"

    preprocess_data(input_path, output_path)
